<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SspPress\Controller\BlogController' => __DIR__ . '/src/SspPress/Controller/PressController.php',
    'SspPress\Module'                       => __DIR__ . '/Module.php',
    'SspPressTest\SampleTest'               => __DIR__ . '/tests/SspPress/SampleTest.php',
    'SspPressTest\Framework\TestCase'       => __DIR__ . '/tests/SspPress/Framework/TestCase.php',
);
